PagWeb/Apps/home/urls.py
from django.contrib import admin
from django.urls import path, include
from Apps.home.views import HomeView, EstudianteView, AdminView, AcercaView

app_name='home'
urlpatterns = [
    path('', HomeView.as_view(), name='homeapp'),
    path('estudiante/', EstudianteView.as_view(), name='estudianteapp'),
    path('admin/', AdminView.as_view(), name='adminapp'),
    path('acerca/', AcercaView.as_view(), name='acercapp')

]

PagWeb/PagWeb/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('Apps.home.urls', 'home')),
]

PagWeb/django_mysql/django_mysql/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

PagWeb/Apps/home/models.py
from django.db import models

# Create your models here.

class Estudiante(models.Model):
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=100)
    creacion = models.DateField(auto_now_add=True)

    def __str__(self):
        return '%s %s' % (self.nombre, self.apellido)


class Administrador(models.Model):
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=100)
    creacion = models.DateField(auto_now_add=True)
    Estudiante = models.ManyToManyField(Estudiante)

    def __str__(self):
        return '%s %s' % (self.nombre, self.apellido)

PagWeb/Apps/home/views.py
import imp
from django.shortcuts import render
from django.views.generic import TemplateView

# Create your views here.

class HomeView(TemplateView):
    template_name='home.html'

class EstudianteView(TemplateView):
    template_name='estudiante.html'

class AdminView(TemplateView):
    template_name='admin.html'

class AcercaView(TemplateView):
    template_name='acerca.html'

PagWeb/Apps/home/templates/acerca.html
{% extends 'base.html' %}

{% block titulo %}
<title>Acerca</title>
{% endblock %}

{% block contenido %} 
<li class="nav-item px-lg-4" align="right"><a class="nav-link text-uppercase" href="{% url 'home:homeapp' %}">Home</a></li>                        
<li class="nav-item px-lg-4"><a class="nav-link text-uppercase" href="{% url 'home:estudianteapp' %}">Estudiantes</a></li>
<li class="nav-item px-lg-4"><a class="nav-link text-uppercase" href="{% url 'home:adminapp' %}">Administradores</a></li>  
    <FONT COLOR="yellow"><h2> <br>Somos una empresa, agarrados de la mano de Dios.</p></FONT>


{% endblock %}

PagWeb/Apps/home/templates/admin.html
{% extends 'base.html' %}

{% block titulo %}
<title>Administradores</title>
{% endblock %}

{% block contenido %}
    
<li class="nav-item px-lg-4"><a class="nav-link text-uppercase" href="{% url 'home:homeapp' %}">Home</a></li> 
<li class="nav-item px-lg-4"><a class="nav-link text-uppercase" href="{% url 'home:estudianteapp' %}">Estudiantes</a></li>
<li class="nav-item px-lg-4"><a class="nav-link text-uppercase" href="{% url 'home:acercapp' %}">Acerca de</a></li>

    <FONT COLOR="blue"><h3><br><b>Listado de Administradores</h3>
        <FONT COLOR="green"><h5>
    <div class="table-responsive">
        <table class="table table-hover table-dark text-center";>
            <thead class="thead-lighy">
        <tr>
            <td><FONT COLOR="cyan"><h2>Id</td>
            <td><FONT COLOR="cyan"><h2>Nombre</td>
            <td><FONT COLOR="cyan"><h2>Apellido</td>
        </FONT></tr>
        <tr>
            <td>1</td>
            <td>Rosario</td>
            <td>Maldonado</td> 
        </tr>
        <tr>
            <td>2</td>
            <td>Beatriz</td>
            <td>Escobar</td> 
        </tr>
        <tr>
            <td>3</td>
            <td>Abner</td>
            <td>Orozco</td> 
        </tr>
        <tr>
            <td>4</td>
            <td>Mario</td>
            <td>Orozco</td> 
        </tr>
        <tr>
            <td>5</td>
            <td>Gabriela</td>
            <td>Velasquez</td> 
        </tr></h5>
    </table>
{% endblock %}

PagWeb/Apps/home/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Home</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <header>
            <h1 class="site-heading text-center text-faded d-none d-lg-block">
                <span class="site-heading-upper text-primary mb-3">BIENVENIDO</span>
                <span class="site-heading-lower"><b>GABRIELA FUENTES</span></b>
            </h1>
        </header>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark py-lg-4" id="mainNav">
            <div class="container">
                <a class="navbar-brand text-uppercase fw-bold d-lg-none" href="index.html">Start Bootstrap</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" 
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mx-auto">
                        {% block contenido %}
                        {% endblock %}
                    </ul>
                </div>
            </div>
        </nav>
       
        <footer class="footer text-faded text-center py-5">
            <div class="container"><p class="m-0 small">Universidad Mariano Galvez</p></div>
        </footer>
    </body>
</html>

PagWeb/Apps/home/templates/estudiante.html
{% extends 'base.html' %}

{% block titulo %}
<title>Estudiantes</title>
{% endblock %}

{% block contenido %}

<li class="nav-item px-lg-4"><a class="nav-link text-uppercase" href="{% url 'home:homeapp' %}">Home</a></li> 
<li class="nav-item px-lg-4"><a class="nav-link text-uppercase" href="{% url 'home:adminapp' %}">Administradores</a></li>
<li class="nav-item px-lg-4"><a class="nav-link text-uppercase" href="{% url 'home:acercapp' %}">Acerca de</a></li>

   
        <B><FONT COLOR="blue"><center><h3><br>Listado de Estudiantes</h3></FONT></center>   
     <FONT COLOR="green"><h4>
        <div class="table-responsive">
            <table class="table table-hover table-dark text-center">
            <thead class="thead-lighy">
        <tr>
            <td><FONT COLOR="cyan">Id</td>
            <td><FONT COLOR="cyan">Nombre</td>
            <td><FONT COLOR="cyan">Apellido</td>
        </tr>
        <tr>
            <td>1</td>
            <td>Gaby</td>
            <td>Fuentes</td> 
        </tr>
        <tr>
            <td>2</td>
            <td>Corina</td>
            <td>De Leon</td> 
        </tr>
        <tr>
            <td>3</td>
            <td>Oscar</td>
            <td>Gabriel</td> 
        </tr>
        <tr>
            <td>4</td>
            <td>Mauricio</td>
            <td>Villatoro</td> 
        </tr>
        <tr>
            <td>5</td>
            <td>Manuel</td>
            <td>Rodas</td> 
        </tr>
       </table></h4></FONT>
{% endblock %}

PagWeb/Apps/home/templates/home.html
{% extends 'base.html' %}

{% block titulo %}
<title>Pagina Web</title>
{% endblock %}

{% block contenido %}
 
<li class="nav-item px-lg-4"><a class="nav-link text-uppercase" href="">Home</a></li> 
<li class="nav-item px-lg-4"><a class="nav-link text-uppercase" href="{% url 'home:estudianteapp' %}">Estudiantes</a></li>
<li class="nav-item px-lg-4"><a class="nav-link text-uppercase" href="{% url 'home:adminapp' %}">Administradores</a></li>
<li class="nav-item px-lg-4"><a class="nav-link text-uppercase" href="{% url 'home:acercapp' %}">Acerca de</a></li>

<p><FONT COLOR="white" text-left ><h2><b><br><br>ELGIDA GABRIELA FUENTES VELASQUEZ
<br>  0903-10-3033
        </h2></p></FONT></b>

{% endblock %}